export const initialClients = [
  {
    id: 1,
    imageSrc: "./asserts/images/avatar1.png",
    phone: "(435) 174-3348",
    email: "napozj1@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Mathilda Bell",
  },
  {
    id: 2,
    imageSrc: "./asserts/images/avatar2.png",
    phone: "(435) 274-3348",
    email: "napozj2@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Stanley Burton",
  },
  {
    id: 3,
    imageSrc: "./asserts/images/avatar3.png",
    phone: "(435) 374-3348",
    email: "napozj3@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Loretta Myers",
  },
  {
    id: 4,
    imageSrc: "./asserts/images/avatar4.png",
    phone: "(435) 474-3348",
    email: "napozj4@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Michael Joss",
  },
  {
    id: 5,
    imageSrc: "./asserts/images/avatar5.png",
    phone: "(435) 574-3348",
    email: "napozj5@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Adam Sandler",
  },
  {
    id: 6,
    imageSrc: "./asserts/images/avatar6.png",
    phone: "(435) 674-3348",
    email: "napozj6@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Danny Moore",
  },
  {
    id: 7,
    imageSrc: "./asserts/images/avatar7.png",
    phone: "(435) 774-3348",
    email: "napozj7@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Anna Ananda",
  },
  {
    id: 8,
    imageSrc: "./asserts/images/avatar1.png",
    phone: "(435) 884-3348",
    email: "napozj8@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "joe biden",
  },
  {
    id: 9,
    imageSrc: "./asserts/images/avatar2.png",
    phone: "(435) 474-2248",
    email: "napozj9@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "joe biden",
  },
  {
    id: 10,
    imageSrc: "./asserts/images/avatar3.png",
    phone: "(475) 474-3348",
    email: "napozj10@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "joe Biden",
  },
  {
    id: 11,
    imageSrc: "./asserts/images/avatar4.png",
    phone: "(435) 714-3348",
    email: "napozj11@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "joe Biden",
  },
  {
    id: 12,
    imageSrc: "./asserts/images/avatar5.png",
    phone: "(435) 994-3348",
    email: "napozj12@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "joe Biden",
  },
  {
    id: 13,
    imageSrc: "./asserts/images/avatar6.png",
    phone: "(435) 132-3348",
    email: "napozj13@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Joe Biden",
  },
  {
    id: 14,
    imageSrc: "./asserts/images/avatar7.png",
    phone: "(435) 167-3348",
    email: "napozj14@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Joe Biden",
  },
  {
    id: 15,
    imageSrc: "./asserts/images/avatar1.png",
    phone: "(142) 888-3348",
    email: "napozj15@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Joe Biden",
  },
  {
    id: 16,
    imageSrc: "./asserts/images/avatar2.png",
    phone: "(111) 474-3348",
    email: "napozj16@paw.com",
    company: "Awesome Company",
    dateUpdate: new Date(),
    fullName: "Joe Biden",
  },
];
